import * as fs from 'fs';
import * as path from 'path';
import { GeneratedTest } from './types';

/**
 * Option B of the auth architecture (see greenci-internal/auth-testing-options.md):
 * when generated specs reference storageState, commit a ready-to-run
 * auth.setup.ts alongside them. The customer adds TEST_USER_EMAIL and
 * TEST_USER_PASSWORD as GitHub secrets and re-runs — credentials only ever
 * exist in their own CI environment.
 */

export const STORAGE_STATE_PATH = 'playwright/.auth/user.json';
export const AUTH_SETUP_FILENAME = 'auth.setup.ts';

/** Do any generated specs opt into an authenticated session? */
export function needsAuthScaffold(tests: GeneratedTest[]): boolean {
  return tests.some((t) => t.code.includes('storageState'));
}

/** Best-guess login path: first journey path containing login/signin, else /login. */
export function loginPathFromJourneys(journeys: string[]): string {
  for (const journey of journeys) {
    const match = journey.match(/(\/[\w./-]*(?:login|sign-?in)[\w./-]*)/i);
    if (match) return match[1];
  }
  return '/login';
}

/**
 * Deterministic, resilient login setup. No LLM involved: the locator chain
 * covers the common form patterns, it is committed plain Playwright the
 * customer can adjust, and a failed run self-reports clearly.
 */
export function authSetupSource(loginPath: string): string {
  return `import { test as setup } from '@playwright/test';

// Generated by GreenCI. Signs in once before the suite and saves the session
// to ${STORAGE_STATE_PATH}, which authenticated specs reference via
// test.use({ storageState: ... }).
//
// Setup: add TEST_USER_EMAIL and TEST_USER_PASSWORD as repository secrets
// (Settings → Secrets and variables → Actions) and expose them as env on the
// GreenCI workflow step. Use a dedicated test account, never a real user.
// If your login form is unusual, edit the locators below — this file is
// yours, like every other test.

const EMAIL = process.env.TEST_USER_EMAIL;
const PASSWORD = process.env.TEST_USER_PASSWORD;

setup('authenticate', async ({ page }) => {
  // Cold dev servers compile the post-login page on demand — give the whole
  // sign-in generous room (CI runners are slow; default 30s test timeout is
  // far too tight for a first-compile navigation).
  setup.setTimeout(120_000);
  setup.skip(!EMAIL || !PASSWORD, 'TEST_USER_EMAIL / TEST_USER_PASSWORD not set — authenticated specs will be skipped');

  await page.goto('${loginPath}');

  const emailField = page
    .getByLabel(/e-?mail|username/i)
    .or(page.getByPlaceholder(/e-?mail|username/i))
    .or(page.locator('input[type="email"], input[name*="email" i], input[name*="user" i]'))
    .first();
  await emailField.fill(EMAIL!);

  const passwordField = page
    .getByLabel(/password/i)
    .or(page.getByPlaceholder(/password/i))
    .or(page.locator('input[type="password"]'))
    .first();
  await passwordField.fill(PASSWORD!);

  await page
    .getByRole('button', { name: /sign in|log ?in|continue|submit/i })
    .first()
    .click();

  // Consider login successful once we are no longer on the login page.
  await page.waitForURL((url) => !/login|sign-?in/i.test(url.pathname), { timeout: 60_000 });

  await page.context().storageState({ path: '${STORAGE_STATE_PATH}' });
});
`;
}

/** Write the setup file into the test dir; returns its absolute path. */
export function writeAuthScaffold(workDir: string, testDir: string, loginPath: string): string {
  const filePath = path.join(workDir, testDir, AUTH_SETUP_FILENAME);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, authSetupSource(loginPath), 'utf-8');
  return filePath;
}

/**
 * Deterministic pre-classification of auth-blocked failures — these must
 * never reach the LLM healer (a selector fix cannot conjure a session, and
 * every attempt costs a Sonnet call).
 */
export function isAuthSetupFailure(error: string | undefined): boolean {
  if (!error) return false;
  return (
    /ENOENT.*\.auth[\\/]user\.json/i.test(error) ||
    /storageState.*(does not exist|no such file|ENOENT)/i.test(error) ||
    /error reading storage state/i.test(error) ||
    /TEST_USER_EMAIL \/ TEST_USER_PASSWORD not set/.test(error)
  );
}
