import * as core from '@actions/core';
import * as path from 'path';
import { ActionConfig, GeneratedTest, ILLMClient, SuspectedBug, TestResult } from './types';
import { parseJourneys, fetchPages } from './bootstrap-context';
import { readExistingTests, formatExistingTestsForAPI } from './existing-tests';
import { runTests, writeTests } from './test-runner';
import { healFailedTests } from './self-healer';
import { createBootstrapPR } from './git-ops';

export interface BootstrapOutcome {
  testsGenerated: number;
  testsPassed: number;
  testsFailed: number;
  testsHealed: number;
  prUrl: string | null;
}

/**
 * Bootstrap mode: build a foundational suite for an app with no tests.
 * Journeys (plain English) + rendered page HTML → generate → run → heal →
 * open a PR with the passing suite.
 */
export async function runBootstrap(
  config: ActionConfig,
  llmClient: ILLMClient,
  workDir: string,
  token: string,
  repo: { owner: string; repo: string },
): Promise<BootstrapOutcome> {
  if (!llmClient.bootstrapTests) {
    throw new Error(`The '${config.llmProvider}' provider does not support bootstrap mode.`);
  }

  const journeys = parseJourneys(config.journeys);
  core.info(`🧭 Bootstrapping suite for ${journeys.length} journey(s)`);

  core.info('📄 Capturing rendered pages for selector grounding...');
  const pages = await fetchPages(config.baseUrl, journeys);
  if (pages.length === 0) {
    core.warning(
      `Could not fetch any pages from ${config.baseUrl} — is your app running in CI? ` +
        'Generation will proceed but selectors will be less grounded.',
    );
  }

  const existing = readExistingTests(workDir, config.testDir);
  const existingTests = existing.length > 0 ? formatExistingTestsForAPI(existing) : undefined;

  const generatedTests = await llmClient.bootstrapTests(journeys, pages, config, existingTests);
  core.info(`Generated ${generatedTests.length} test file(s)`);
  if (generatedTests.length === 0) {
    return { testsGenerated: 0, testsPassed: 0, testsFailed: 0, testsHealed: 0, prUrl: null };
  }

  await writeTests(generatedTests, workDir, config.testDir);

  core.info('🏃 Running the bootstrap suite...');
  const initialResults = await runTests(generatedTests, config, workDir);

  const failedTests = initialResults
    .map((result, i) => ({ test: generatedTests[i], result }))
    .filter(({ result }) => !result.passed);

  let healed: GeneratedTest[] = [];
  let healedResults: TestResult[] = [];
  let suspectedBugs: SuspectedBug[] = [];
  if (failedTests.length > 0 && config.maxRetries > 0) {
    core.info(`🔧 Healing ${failedTests.length} failing bootstrap test(s)...`);
    const healing = await healFailedTests(failedTests, emptyChangeContext(), config, llmClient, workDir);
    healed = healing.healed;
    healedResults = healing.results;
    suspectedBugs = healing.suspectedBugs;
  }

  const allResults = [...initialResults.filter((r) => r.passed), ...healedResults];
  const passed = allResults.filter((r) => r.passed);
  const failed = allResults.filter((r) => !r.passed);

  // Commit only the verified-passing suite; report the rest for human review
  const passingFiles = passed.map((r) => path.join(workDir, config.testDir, r.filename));

  let prUrl: string | null = null;
  if (config.autoCommit && token && passingFiles.length > 0) {
    const body = buildBootstrapPRBody(journeys, passed, failed, healed, suspectedBugs);
    const result = await createBootstrapPR(token, repo.owner, repo.repo, passingFiles, workDir, body);
    prUrl = result.prUrl;
  } else if (passingFiles.length === 0) {
    core.warning('No bootstrap tests passed — nothing committed. See the run log for failures.');
  }

  return {
    testsGenerated: generatedTests.length,
    testsPassed: passed.length,
    testsFailed: failed.length,
    testsHealed: healed.length,
    prUrl,
  };
}

function emptyChangeContext() {
  return { routes: [], components: [], apiEndpoints: [], modifiedFiles: [], summary: 'bootstrap' };
}

function buildBootstrapPRBody(
  journeys: string[],
  passed: TestResult[],
  failed: TestResult[],
  healed: GeneratedTest[],
  suspectedBugs: SuspectedBug[],
): string {
  let body = '## 🌱 Foundational E2E suite generated by GreenCI\n\n';
  body += 'This PR contains the **verified-passing** starter suite for your critical journeys. ';
  body += 'Review it like any code: the tests are plain Playwright and fully yours.\n\n';

  body += '### Journeys covered\n';
  body += journeys.map((j) => `- ${j}`).join('\n') + '\n\n';

  body += `### Results\n| | |\n|---|---|\n| Passing (committed) | ✅ ${passed.length} |\n`;
  if (healed.length > 0) body += `| Self-healed before passing | 🔧 ${healed.length} |\n`;
  if (failed.length > 0) body += `| Failing (NOT committed) | ❌ ${failed.length} |\n`;
  body += '\n';

  if (suspectedBugs.length > 0) {
    body += '### 🚨 Possible app bugs found during bootstrap\n';
    for (const bug of suspectedBugs) {
      body += `- \`${bug.filename}\` — ${bug.reasoning}\n`;
    }
    body += '\n';
  }

  if (failed.length > 0) {
    body += '### Failing tests (see the workflow log)\n';
    body += failed.map((f) => `- \`${f.filename}\``).join('\n') + '\n\n';
    body += 'Common causes: journeys behind login (set up Playwright `storageState` — see TODOs in the specs), or pages that need seeded data.\n\n';
  }

  body += '---\n*Generated by [GreenCI](https://greenci.ai) 🌱 — future PRs will keep this suite up to date automatically.*\n';
  return body;
}
