import { MigrationReport } from './types';

const COMMENT_MARKER = '<!-- greenci-migration-report -->';

export function buildMigrationReportBody(report: MigrationReport): string {
  const duration = (report.duration / 1000).toFixed(1);
  const statusEmoji = report.failed === 0 ? '✅' : '⚠️';

  let body = `${COMMENT_MARKER}\n`;
  body += `## ${statusEmoji} GreenCI Cypress → Playwright Migration Report\n\n`;

  // Summary
  body += `| Metric | Value |\n`;
  body += `|--------|-------|\n`;
  body += `| Total Files | ${report.totalFiles} |\n`;
  body += `| Converted | ✅ ${report.converted} |\n`;
  body += `| Needs Review | ⚠️ ${report.needsReview} |\n`;
  body += `| Failed | ❌ ${report.failed} |\n`;
  body += `| Duration | ${duration}s |\n\n`;

  // File details
  if (report.files.length > 0) {
    body += `### File Details\n\n`;
    body += `| Source | Target | Status | Confidence | Notes |\n`;
    body += `|--------|--------|--------|------------|-------|\n`;

    for (const file of report.files) {
      const statusIcon = file.status === 'converted' ? '✅' : file.status === 'needs-review' ? '⚠️' : '❌';
      const confidence = `${Math.round(file.confidence * 100)}%`;
      const notes = file.notes.length > 0 ? file.notes[0] : '-';
      body += `| \`${file.source}\` | \`${file.target}\` | ${statusIcon} ${file.status} | ${confidence} | ${notes} |\n`;
    }
    body += '\n';
  }

  // Manual review items
  const reviewFiles = report.files.filter((f) => f.status === 'needs-review');
  if (reviewFiles.length > 0) {
    body += `### ⚠️ Items Needing Manual Review\n\n`;
    for (const file of reviewFiles) {
      body += `- **\`${file.target}\`**\n`;
      for (const note of file.notes) {
        body += `  - ${note}\n`;
      }
    }
    body += '\n';
  }

  // Failed items
  const failedFiles = report.files.filter((f) => f.status === 'failed');
  if (failedFiles.length > 0) {
    body += `### ❌ Failed Conversions\n\n`;
    for (const file of failedFiles) {
      body += `- **\`${file.source}\`**: ${file.notes.join('; ')}\n`;
    }
    body += '\n';
  }

  // Tips
  body += `### 📋 Next Steps\n\n`;
  body += `1. Review converted files, especially those marked with ⚠️\n`;
  body += `2. Set up \`playwright.config.ts\` if not already present\n`;
  body += `3. Install Playwright: \`npm install -D @playwright/test && npx playwright install\`\n`;
  body += `4. Run converted tests: \`npx playwright test\`\n`;
  body += `5. Remove Cypress dependencies when migration is complete\n`;
  body += `6. Look for \`// TODO:\` comments in converted files for items needing manual fixes\n\n`;

  body += `---\n`;
  body += `*Generated by [GreenCI](https://greenci.ai) 🌱*\n`;

  return body;
}
