import * as github from '@actions/github';
import { PRContext, RunReport } from './types';

const COMMENT_MARKER = '<!-- greenci-report -->';

export async function postReport(
  token: string,
  prContext: PRContext,
  report: RunReport
): Promise<string> {
  const octokit = github.getOctokit(token);
  const body = buildReportBody(report);

  // Check for existing GreenCI comment to update
  const { data: comments } = await octokit.rest.issues.listComments({
    owner: prContext.owner,
    repo: prContext.repo,
    issue_number: prContext.prNumber,
  });

  const existingComment = comments.find((c) => c.body?.includes(COMMENT_MARKER));

  if (existingComment) {
    const { data } = await octokit.rest.issues.updateComment({
      owner: prContext.owner,
      repo: prContext.repo,
      comment_id: existingComment.id,
      body,
    });
    return data.html_url;
  }

  const { data } = await octokit.rest.issues.createComment({
    owner: prContext.owner,
    repo: prContext.repo,
    issue_number: prContext.prNumber,
    body,
  });

  return data.html_url;
}

function buildReportBody(report: RunReport): string {
  const hasSuspectedBugs = (report.suspectedBugs?.length ?? 0) > 0;
  const statusEmoji = hasSuspectedBugs ? '🚨' : report.testsFailed === 0 ? '✅' : '⚠️';
  const duration = (report.duration / 1000).toFixed(1);

  let body = `${COMMENT_MARKER}\n`;
  body += `## ${statusEmoji} GreenCI E2E Test Report\n\n`;

  // Possible real regressions come first — they are the most important signal
  if (hasSuspectedBugs && report.suspectedBugs) {
    body += `### 🚨 Possible App Regressions Detected\n\n`;
    body += `The self-healer declined to "fix" ${report.suspectedBugs.length} failing test(s) because the failure looks like a real application bug, not a test problem:\n\n`;
    for (const bug of report.suspectedBugs) {
      body += `- \`${bug.filename}\` — ${bug.reasoning}\n`;
      if (bug.error) {
        const errorPreview = bug.error.split('\n').slice(0, 5).join('\n');
        body += `  <details><summary>Error output</summary>\n\n  \`\`\`\n  ${errorPreview}\n  \`\`\`\n  </details>\n`;
      }
    }
    body += `\nPlease review these before merging.\n\n`;
  }

  // Summary table
  body += `| Metric | Value |\n`;
  body += `|--------|-------|\n`;
  body += `| Tests Generated | ${report.testsGenerated} |\n`;
  body += `| Tests Passed | ✅ ${report.testsPassed} |\n`;
  body += `| Tests Failed | ${report.testsFailed > 0 ? '❌' : '✅'} ${report.testsFailed} |\n`;
  if (report.testsHealed > 0) {
    body += `| Tests Self-Healed | 🔧 ${report.testsHealed} |\n`;
  }
  body += `| Duration | ${duration}s |\n\n`;

  // Test details
  if (report.tests.length > 0) {
    body += `### Test Results\n\n`;
    for (const test of report.tests) {
      const icon = test.passed ? '✅' : '❌';
      const dur = (test.duration / 1000).toFixed(1);
      body += `- ${icon} \`${test.filename}\` (${dur}s)\n`;
      if (!test.passed && test.error) {
        const errorPreview = test.error.split('\n').slice(0, 5).join('\n');
        body += `  <details><summary>Error</summary>\n\n  \`\`\`\n  ${errorPreview}\n  \`\`\`\n  </details>\n\n`;
      }
    }
    body += '\n';
  }

  // Healing evidence — what was changed and why, so heals are reviewable
  if (report.healedTests && report.healedTests.length > 0) {
    body += `### 🔧 Self-Healed Tests\n\n`;
    for (const healedTest of report.healedTests) {
      const reason = healedTest.verdict?.reasoning || healedTest.description;
      body += `- \`${healedTest.filename}\` — ${reason}\n`;
    }
    body += `\nHealed tests are committed to this PR — review the diff like any other change.\n\n`;
  }

  // Committed files
  if (report.committedFiles.length > 0) {
    body += `### 📝 Committed Files\n\n`;
    for (const file of report.committedFiles) {
      body += `- \`${file}\`\n`;
    }
    body += '\n';
  }

  // Files analyzed
  if (report.filesChanged.length > 0) {
    body += `<details><summary>📂 Files Analyzed (${report.filesChanged.length})</summary>\n\n`;
    for (const file of report.filesChanged) {
      body += `- \`${file}\`\n`;
    }
    body += `</details>\n\n`;
  }

  body += `---\n`;
  body += `*Generated by [GreenCI](https://greenci.ai) 🌱*\n`;

  return body;
}
