import * as core from '@actions/core';
import * as exec from '@actions/exec';
import * as fs from 'fs';
import * as path from 'path';
import { ActionConfig, GeneratedTest, TestResult } from './types';

/**
 * Zero-test repos (the bootstrap audience) usually have neither
 * @playwright/test nor browsers installed. Install what's missing so the
 * first run works out of the box. Returns true if anything was installed.
 */
export async function ensurePlaywright(workDir: string): Promise<boolean> {
  let installed = false;

  const hasPackage = fs.existsSync(path.join(workDir, 'node_modules', '@playwright', 'test'));
  if (!hasPackage) {
    core.info('📦 @playwright/test not found in this repo — installing (not saved to package.json)...');
    await exec.exec('npm', ['install', '--no-save', '--no-audit', '--no-fund', '@playwright/test'], {
      cwd: workDir,
      silent: true,
    });
    installed = true;
  }

  core.info('🌐 Ensuring Chromium is installed for Playwright...');
  await exec.exec('npx', ['playwright', 'install', '--with-deps', 'chromium'], {
    cwd: workDir,
    silent: true,
  });

  return installed;
}

/**
 * Without a Playwright config, relative page.goto('/...') calls fail because
 * there is no baseURL. If the repo has no config, write a minimal one so the
 * generated tests run. Returns true if a config was created (callers should
 * tell the user to add a permanent one).
 */
export function ensurePlaywrightConfig(
  workDir: string,
  baseUrl: string,
  testDir: string,
  withAuthSetup = false,
): boolean {
  const exists = ['playwright.config.ts', 'playwright.config.js', 'playwright.config.mjs'].some((f) =>
    fs.existsSync(path.join(workDir, f)),
  );
  if (exists) return false;

  const projects = withAuthSetup
    ? `
  projects: [
    { name: 'setup', testMatch: /auth\\.setup\\.ts/ },
    { name: 'chromium', dependencies: ['setup'] },
  ],`
    : '';

  const config = `import { defineConfig } from '@playwright/test';

// Generated by GreenCI for this run. Add your own playwright.config.ts to customize.
export default defineConfig({
  testDir: '${testDir}',${projects}
  use: {
    baseURL: '${baseUrl}',
    trace: 'retain-on-failure',
  },
});
`;
  fs.writeFileSync(path.join(workDir, 'playwright.config.ts'), config, 'utf-8');
  core.info(`⚙️ No Playwright config found — wrote a minimal playwright.config.ts (baseURL: ${baseUrl})`);
  return true;
}

export async function writeTests(tests: GeneratedTest[], workDir: string, testDir: string = 'e2e'): Promise<string[]> {
  const writtenFiles: string[] = [];

  for (const test of tests) {
    // Models sometimes emit filenames already prefixed with the test dir
    // (e.g. "e2e/auth.spec.ts") — strip it to avoid e2e/e2e/ nesting.
    if (test.filename.startsWith(`${testDir}/`)) {
      test.filename = test.filename.slice(testDir.length + 1);
    }
    const filePath = path.join(workDir, testDir, test.filename);
    const dir = path.dirname(filePath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const isUpdate = fs.existsSync(filePath);
    fs.writeFileSync(filePath, test.code, 'utf-8');
    writtenFiles.push(filePath);
    core.info(`${isUpdate ? '♻️ Updated' : '✨ Created'} test: ${test.filename}`);
  }

  return writtenFiles;
}

export async function runTests(
  tests: GeneratedTest[],
  config: ActionConfig,
  workDir: string
): Promise<TestResult[]> {
  const results: TestResult[] = [];

  for (const test of tests) {
    const filePath = path.join(workDir, config.testDir, test.filename);
    const startTime = Date.now();

    let stdout = '';
    let stderr = '';

    try {
      // Pass just the filename as a regex filter — Playwright matches against absolute paths
      const basename = path.basename(filePath);
      const exitCode = await exec.exec('npx', ['playwright', 'test', basename, '--reporter=line'], {
        cwd: workDir,
        env: {
          ...process.env,
          BASE_URL: config.baseUrl,
          CI: 'true',
        },
        silent: true,
        listeners: {
          stdout: (data) => {
            stdout += data.toString();
          },
          stderr: (data) => {
            stderr += data.toString();
          },
        },
        ignoreReturnCode: true,
      });

      const duration = Date.now() - startTime;
      const passed = exitCode === 0;

      results.push({
        filename: test.filename,
        passed,
        duration,
        error: passed ? undefined : stderr || stdout,
        stdout,
      });

      if (passed) {
        core.info(`✅ ${test.filename} passed (${duration}ms)`);
      } else {
        core.warning(`❌ ${test.filename} failed (${duration}ms)`);
        // Log stderr first (usually has the real error), then stdout
        const errorOutput = [stderr, stdout].filter(Boolean).join('\n');
        const errorSnippet = errorOutput.substring(0, 800);
        if (errorSnippet) {
          core.info(`   Error output:\n${errorSnippet}`);
        }
      }
    } catch (error) {
      const duration = Date.now() - startTime;
      results.push({
        filename: test.filename,
        passed: false,
        duration,
        error: error instanceof Error ? error.message : String(error),
      });
      core.warning(`❌ ${test.filename} errored: ${error}`);
    }
  }

  return results;
}

export function cleanupTests(filePaths: string[]): void {
  for (const filePath of filePaths) {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  }
}
